env:
  browser: true
  es2021: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  import/extensions: off
  camelcase: off
  no-shadow: off
  prefer-destructuring: off
  import/no-unresolved: off
  class-methods-use-this: off
  no-restricted-globals: off
  import/prefer-default-export: off
  no-param-reassign: off
  no-underscore-dangle: off
  max-len: ["error", {
    "code": 120,
    "ignoreComments": true,
    "ignoreTrailingComments": true,
    "ignoreUrls": true,
    "ignoreStrings": true,
    "ignoreTemplateLiterals": true
  }]
